name: "Inflate Secrets"
description: "Inflates the secret values into the appropriate files"
inputs:
  keystore:
    description: "The keystore to inflate"
    required: true
  google-services:
    description: "The google-services.json to inflate"
    required: true
  firebase-creds:
    description: "The firebase credentials to inflate"
    required: false
  playstore-creds:
    description: "The playstore credentials to inflate"
    required: false
runs:
  using: "composite"
  steps:
    # Mock google-services step removed - using real google-services.json for all flavors

    - name: Inflate release_keystore.keystore
      shell: bash
      env:
        KEYSTORE: ${{ inputs.keystore }}
      run: |
        echo $KEYSTORE | base64 --decode > app/release_keystore.keystore
        echo $KEYSTORE | base64 --decode > wear/release_keystore.keystore
        echo $KEYSTORE | base64 --decode > automotive/release_keystore.keystore

    - name: Inflate google-services.json
      shell: bash
      env:
        GOOGLE_SERVICES: ${{ inputs.google-services }}
      run: |
        echo $GOOGLE_SERVICES > app/google-services.json
        echo $GOOGLE_SERVICES > wear/google-services.json
        echo $GOOGLE_SERVICES > automotive/google-services.json
        # Also copy to flavor-specific directories for minimal builds
        echo $GOOGLE_SERVICES > app/src/minimal/google-services.json
        echo $GOOGLE_SERVICES > app/src/debug/google-services.json

    - name: Inflate firebaseAppDistributionServiceCredentialsFile.json
      if: ${{ inputs.firebase-creds != '' }}
      shell: bash
      env:
        CREDS: ${{ inputs.firebase-creds }}
      run: |
        echo $CREDS > firebaseAppDistributionServiceCredentialsFile.json

    - name: Inflate playStorePublishServiceCredentialsFile.json
      if: ${{ inputs.playstore-creds != '' }}
      shell: bash
      env:
        CREDS: ${{ inputs.playstore-creds }}
      run: |
        echo $CREDS > app/playStorePublishServiceCredentialsFile.json
        echo $CREDS > wear/playStorePublishServiceCredentialsFile.json
        echo $CREDS > automotive/playStorePublishServiceCredentialsFile.json
